### ISSUE TITLE
Using lists of Lens IDs and cursor based pagination - Patent API

### ISSUE THREAD

**Issue by szyontz** [cambialens/lens-api-doc#41]
Hello,

I modified the Python code of a few other users here to pull the complete records of 49K patents from the API using a specific list of Lens IDs.  The code below works for shorter lists of IDs, but I get a 400 error after about 45 minutes if I try to use the whole list.  What might be some reasons for the error for the full list?  

Also, the code is pulling records, but the error kept me from saving any of the information, so I've run over my allowed records for the trial by accident (so now I get a 429 error).  Is there anything I can do about that?

``` py
url = 'https://api.lens.org/patent/search'
request_body = '''{
              "query": {
                  "terms":  {
                      "lens_id":'''+(json.dumps(ids))+'''
                  }
              },
              "size" : 100,
              "scroll" : "1m"
}'''

headers = {'Authorization': 'Bearer {token}', 'Content-Type': 'application/json'}
def scroll(scroll_id):
    if scroll_id is not None:
        global request_body
        request_body = '''{"scroll_id": "%s"}''' % scroll_id
    response = requests.post(url, data=request_body, headers=headers)
    if response.status_code !=requests.codes.ok:
        print(response.status_code)
    elif response.status_code == requests.codes.too_many_requests:
        time.sleep(8)
        scroll(scroll_id)
    else: 
        json = response.json()
        scroll_id = json["scroll_id"]
        if len(json['data']) == 0:
            return [json]
        return[json] + scroll(scroll_id)
        
json = scroll(scroll_id=None)
json = json[:-1]
```
Thank you!

**Comment by rosharma9** [comment]
The reason might be your request is too large when you push ~50K ids at once. I would recommend to iterate through chunks (~10K at a time).
Since you are doing multiple calls at a time you might be getting rate limited per min so try adjusting `time.sleep(8)` to larger value as per your need. Also I can see from the code that you are checking `response.status_code !=requests.codes.ok:` before the `requests.codes.too_many_requests`, you would need to check it first and then other non-ok codes. Please refer to our api doc for cursor example:
https://docs.api.lens.org/samples-patent.html#cursor-based-pagination

**Comment by szyontz** [comment]
Thank you for your quick reply!  Doing 10K at a time was going to be my next attempt, but unfortunately I accidentally exceeded my record allowance that came with the trial, so none of my code will run right now.  Is there anything I can do about that?

**Comment by rosharma9** [comment]
You can re-request new [subscription](https://www.lens.org/lens/user/subscriptions#patents) or contact [subscription support ](https://docs.api.lens.org/support.html) explaining your situation.

**Comment by rosharma9** [comment]
Closing this as you've re-requested another subscription.
